apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pod.rules
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
    - name: pod
      rules:
        - alert: Pod:Restart:WARN
          expr: increase(kube_pod_container_status_restarts_total[30m]) >= 5          
          labels:
            severity: warning
            groupName: pod
          annotations:
            summary: "Pod Restart more than 5 times in the last 30minutes."
            description: "Pod {{ $labels.pod }} in Namespace {{ $labels.namespace }} has restarted more than 5 times in the last 30 minutes."
        - alert: Pod:Pending:WARN
          expr: kube_pod_status_phase{phase="Pending"} == 1
          for: 5m
          labels:
            severity: warning
            groupName: pod
          annotations:
            summary: "Pod Pending more than 5 minutes"
            description: "Pod {{ $labels.pod }} in Namespace {{ $labels.namespace }} has been pending for more than 5 minutes."
        - alert: Pod:OOMKilled:WARN
          expr: (kube_pod_container_status_restarts_total - kube_pod_container_status_restarts_total offset 10m >= 1) and ignoring (reason) min_over_time(kube_pod_container_status_last_terminated_reason{reason="OOMKilled"}[10m]) == 1
          labels:
            severity: warning
            groupName: pod
          annotations:
            summary: "Pod has been restarted due to OOMKilled in the last 10 minutes"
            description: "Container {{ $labels.container }} in pod {{ $labels.namespace }}/{{ $labels.pod }} has been OOMKilled {{ $value }} times in the last 10 minutes."
