- job_name: "blackbox-exporter"
  scrape_interval: 15s
  metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
    - targets:
        - https://7992-1-224-68-15.ngrok-free.app
        - https://7992-1-224-68-15.ngrok-free.app/failed
        - https://7992-1-224-68-15.ngrok-free.app/slow
        - https://7992-1-224-68-15.ngrok-free.app/timeout
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: prometheus-blackbox-exporter.blackbox.svc.cluster.local:9115 
